### ISSUE TITLE
fnNetEnd is not a function

### ISSUE THREAD

**Issue by malayladu** [zigbang/zigbang-email-verifier#3]
I received an error while verifying email of "test[at]parceirosweb[dot]com[dot]br"

> RESOLVE MX RECORD
	mx1.hostinger.com.br
CONNECTED SMTP SERVER
	220-mx1.main-hosting.eu ESMTP [Main-Hosting.eu Mail System]
HELO parceirosweb.com.br
/home/user/test/node_modules/zb-email-verifier/lib/netsend.js:77
      fnNetEnd();
      ^
  TypeError: fnNetEnd is not a function
    at Socket.client.on (/home/user/test/node_modules/zb-email-verifier/lib/netsend.js:77:7)
    at emitNone (events.js:91:20)
    at Socket.emit (events.js:185:7)
    at endReadableNT (_stream_readable.js:974:12)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)

**Comment by malayladu** [comment]
@yunjunseokzb Any idea on this issue?

**Comment by yunjunseokzb** [comment]
I can not found your error, but i fixed expected error

**Comment by malayladu** [comment]
When will this part of a package?

Can you please fix the issue and release a new version of a package such that I will test again and confirm the fix.

Thanks in advance.

**Comment by malayladu** [comment]
Awesome 👍 

Thanks!
